// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDBvACuTDcLV6r1pYjG95JBn9cBZis6M',
    appId: '1:204150920816:web:0560fb7a14c34ec80a06b5',
    messagingSenderId: '204150920816',
    projectId: 'world-lingo',
    authDomain: 'world-lingo.firebaseapp.com',
    storageBucket: 'world-lingo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpqRmfEweeK7TS4d4g6Y4mb6_0ju8M8U',
    appId: '1:204150920816:android:6097fb0a3f34a0c60a06b5',
    messagingSenderId: '204150920816',
    projectId: 'world-lingo',
    storageBucket: 'world-lingo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrh3PZwlqFh49lwCb5kIgN_G4unDMx4yQ',
    appId: '1:204150920816:ios:31895f6804c2f1750a06b5',
    messagingSenderId: '204150920816',
    projectId: 'world-lingo',
    storageBucket: 'world-lingo.appspot.com',
    iosClientId: '204150920816-pr2dnu2u8bndc6n49es9uu31i4tro2uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldlingo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrh3PZwlqFh49lwCb5kIgN_G4unDMx4yQ',
    appId: '1:204150920816:ios:31895f6804c2f1750a06b5',
    messagingSenderId: '204150920816',
    projectId: 'world-lingo',
    storageBucket: 'world-lingo.appspot.com',
    iosClientId: '204150920816-pr2dnu2u8bndc6n49es9uu31i4tro2uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldlingo3',
  );
}
